"""Bot source code generator - generates aiogram Python code from bot configuration."""
from typing import Optional
from app.models.bot import Bot


def generate_bot_source_code(bot: Bot, ai_config: Optional[dict] = None) -> str:
    """
    Generate aiogram Python source code for a bot based on its configuration.
    
    Args:
        bot: Bot model instance
        ai_config: Optional AI configuration dict
        
    Returns:
        Generated Python source code as string
    """
    bot_name = bot.username or "my_bot"
    safe_name = bot_name.replace("-", "_").replace(".", "_")
    
    # Get bot config
    config = bot.config or {}
    welcome_message = config.get("welcome_message", "Welcome! I'm your assistant.")
    description = config.get("description", "")
    
    # AI configuration
    ai_enabled = config.get("ai_enabled", False)
    ai_model = config.get("ai_model", "gpt-3.5-turbo")
    system_prompt = config.get("system_prompt", "You are a helpful assistant.")
    
    code = f'''#!/usr/bin/env python3
"""
Auto-generated Telegram Bot: {bot_name}
{description}

Generated by ADMINCHAT PANEL
"""
import asyncio
import logging
from aiogram import Bot, Dispatcher, types, F
from aiogram.filters import CommandStart, Command
from aiogram.types import Message, CallbackQuery
from aiogram.enums import ParseMode

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Bot configuration
BOT_TOKEN = "{bot.token[:10]}..."  # Token truncated for security
BOT_USERNAME = "{bot_name}"
WELCOME_MESSAGE = """{welcome_message}"""

# AI Configuration
AI_ENABLED = {str(ai_enabled)}
AI_MODEL = "{ai_model}"
SYSTEM_PROMPT = """{system_prompt}"""


# Initialize bot and dispatcher
bot = Bot(token=BOT_TOKEN)
dp = Dispatcher()


@dp.message(CommandStart())
async def cmd_start(message: Message):
    """Handle /start command."""
    await message.answer(
        WELCOME_MESSAGE,
        parse_mode=ParseMode.HTML
    )
    logger.info(f"User {{message.from_user.id}} started the bot")


@dp.message(Command("help"))
async def cmd_help(message: Message):
    """Handle /help command."""
    help_text = """
🤖 <b>Bot Help</b>

Available commands:
/start - Start the bot
/help - Show this help message
/settings - View bot settings

{description}
"""
    await message.answer(help_text, parse_mode=ParseMode.HTML)


@dp.message(Command("settings"))
async def cmd_settings(message: Message):
    """Handle /settings command."""
    settings_text = f"""
⚙️ <b>Bot Settings</b>

Username: @{BOT_USERNAME}
AI Enabled: {{AI_ENABLED}}
AI Model: {{AI_MODEL}}
"""
    await message.answer(settings_text, parse_mode=ParseMode.HTML)


@dp.message(F.text)
async def handle_message(message: Message):
    """Handle text messages."""
    user_text = message.text
    user_id = message.from_user.id
    username = message.from_user.username or "unknown"
    
    logger.info(f"Message from {{username}} ({{user_id}}): {{user_text}}")
    
    if AI_ENABLED:
        # TODO: Integrate with AI service
        # For now, echo back with AI indicator
        response = f"🤖 [AI: {{AI_MODEL}}]\\n\\nProcessing: {{user_text}}"
    else:
        # Default response when AI is disabled
        response = f"Received your message: {{user_text}}\\n\\nAI is currently disabled."
    
    await message.answer(response)


@dp.callback_query(F.data)
async def handle_callback(callback: CallbackQuery):
    """Handle callback queries."""
    await callback.answer()
    logger.info(f"Callback received: {{callback.data}}")


async def main():
    """Main entry point."""
    logger.info(f"Starting bot: @{BOT_USERNAME}")
    logger.info(f"AI Enabled: {{AI_ENABLED}}")
    
    # Start polling
    await dp.start_polling(bot)


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except (KeyboardInterrupt, SystemExit):
        logger.info("Bot stopped")
'''
    return code


def generate_minimal_bot_source(bot: Bot) -> str:
    """Generate minimal bot source code for quick deployment."""
    bot_name = bot.username or "my_bot"
    
    code = f'''#!/usr/bin/env python3
"""Minimal Telegram Bot: {bot_name}"""
import asyncio
from aiogram import Bot, Dispatcher, types
from aiogram.filters import CommandStart

BOT_TOKEN = "{bot.token[:10]}..."
bot = Bot(token=BOT_TOKEN)
dp = Dispatcher()

@dp.message(CommandStart())
async def start(message: types.Message):
    await message.answer("Hello! I'm {bot_name}.")

async def main():
    await dp.start_polling(bot)

if __name__ == "__main__":
    asyncio.run(main())
'''
    return code
